name: Build and Push Docker Image

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ] # triggers on version tags like v1.0.0

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker Image
      run: |
        IMAGE=schekurthi/nsctl
        TAG=latest

        # Optional: If pushing from a tag like v1.0.0, use that tag too
        if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
          TAG="${GITHUB_REF#refs/tags/}"
        fi

        docker build -t $IMAGE:$TAG .

        # Push latest and tag-specific
        docker tag $IMAGE:$TAG $IMAGE:latest
        docker push $IMAGE:$TAG
        docker push $IMAGE:latest
